services:
  api:
    build:
      context: .  # Ubicación del Dockerfile
    container_name: python-api
    ports:
      - "5000:5000"  # cambia si usás otro puerto
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api:/app  # monta tu código en tiempo real
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysqldb  # si la API también habla con MySQL

  mysqldb:
    image: mysql:8.0.2
    container_name: mysql-api
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=flask
    ports:
      - "3608:3306"  # distinto del otro MySQL si corren en paralelo
    volumes:
      - db_api:/var/lib/mysql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  db_api:
