services:
  mysqldb:
    image: mysql:8.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    #command: --default-authentication-plugin=mysql_native_password --skip-ssl
  mysqldb_prod:
    image: mysql:8.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD_PROD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE_PROD
    ports:
      - $MYSQLDB_LOCAL_PORT_PROD:$MYSQLDB_DOCKER_PORT_PROD
    volumes:
      - db_prod:/var/lib/mysql
      - ./sql/data_prod.sql:/docker-entrypoint-initdb.d/data_prod.sql
    #command: --default-authentication-plugin=mysql_native_password --skip-ssl
volumes:
  db:
  db_prod:
  