services:
  api:
    build:
      context: .
    container_name: python-api
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.2
    container_name: mysql-api
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=flask
    ports:
      - "3608:3306"
    volumes:
      - db_api:/var/lib/mysql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  db_api: